# -*- mode: ruby -*-
# vi: set ft=ruby :

# ./bin/vagrant box add centos65-x86_64-50g https://googledrive.com/host/0B4tZlTbOXHYWVGpHRWZuTThGVUE/centos65_virtualbox_50G.box

box = "centos71-x86_64"

Vagrant.configure("2") do |config|

  #config.yum_proxy.http     = ENV['VAGRANT_HTTP_PROXY'] || ""
  #config.yum_proxy.https     = ENV['VAGRANT_HTTPS_PROXY'] || ""
  #config.yum_proxy.no_proxy     = ENV['VAGRANT_HTTP_NO_PROXY'] || ""
  
  # See:
  # http://devops.me/2011/10/10/vagrant-tricks-and-troubleshooting/
  # http://cbednarski.com/articles/creating-vagrant-base-box-for-centos-62/

  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Virtualbox Configuration
  config.vm.provider :virtualbox do |vb|
    config.vbguest.no_remote = true
    config.vbguest.auto_update = false
  end
  #config.vbguest.no_remote = true
  #config.vbguest.auto_update = false
  # Libvirt Configuration
  config.vm.provider :libvirt do |libvirt|
    # Don't forget to create your storage pool
    libvirt.storage_pool_name="ryba-cluster"
    libvirt.uri="qemu:///system"
    # NOT WORKING BUT SHOULD: libvirt.graphics_type= 'none' 
    # if ARGV[0] == "up"
    #  config.vm.provision "shell", path: "setswap.sh"
    # end
  end
  config.vm.define :monit1 do |node|
    node.vm.box = box
    node.vm.hostname = "monit1.ryba"
    node.vm.network :private_network, ip: "10.10.10.20"
    node.vm.network :forwarded_port, guest: 22, host: 24011, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1280
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 1536
      d.graphics_port = 5911
    end
  end
end
